apiVersion: apps/v1
kind: Deployment
metadata:
  name: resttemplateserver
  labels:
    app: resttemplateserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resttemplateserver
  template:
    metadata:
      labels:
        app: resttemplateserver
      annotations:
        sidecar.istio.io/inject: "true"  
    spec:
      containers:
        - name: resttemplateserver
          image: 210.90.24.172:8080/restproject/leeyoungkon/resttemplateserver:90eb31a250a75095d133e531c2698890c6cfa704
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD    
              value: 123456
          
---
apiVersion: v1
kind: Service
metadata:
  name: resttemplateserver
spec:
  type: NodePort
  selector:
    app: resttemplateserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30102

